CREATE TABLE ranks (
  name varchar(32) NOT NULL DEFAULT '',
  sex  varchar(1)  NOT NULL DEFAULT 'M',
  year integer     NOT NULL DEFAULT 0,
  rank integer     NOT NULL DEFAULT 0
);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1880, 0);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1890, 0);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1900, 1478);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1910, 0);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1920, 1299);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1930, 644);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1940, 163);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1950, 79);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1960, 20);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1970, 8);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1980, 12);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 1990, 27);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 2000, 43);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Brian", "M", 2010, 101);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1880, 97);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1890, 104);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1900, 120);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1910, 164);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1920, 185);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1930, 165);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1940, 155);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1950, 129);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1960, 111);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1970, 232);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1980, 461);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 1990, 661);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 2000, 937);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Dan", "M", 2010, 1431);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1880, 25);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1890, 39);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1900, 44);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1910, 54);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1920, 52);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1930, 47);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1940, 34);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1950, 21);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1960, 17);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1970, 19);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1980, 11);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 1990, 5);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 2000, 9);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Daniel", "M", 2010, 8);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1880, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1890, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1900, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1910, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1920, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1930, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1940, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1950, 2);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1960, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1970, 9);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1980, 25);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 1990, 35);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 2000, 47);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mary", "F", 2010, 109);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1880, 46);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1890, 48);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1900, 51);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1910, 45);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1920, 50);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1930, 54);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1940, 18);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1950, 4);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1960, 2);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1970, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1980, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 1990, 1);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 2000, 2);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Michael", "M", 2010, 3);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1880, 142);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1890, 170);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1900, 158);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1910, 144);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1920, 141);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1930, 196);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1940, 122);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1950, 113);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1960, 36);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1970, 137);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1980, 401);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 1990, 507);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 2000, 599);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mike", "M", 2010, 869);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1880, 81);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1890, 118);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1900, 138);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1910, 170);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1920, 275);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1930, 357);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1940, 439);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1950, 570);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1960, 782);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1970, 752);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1980, 635);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 1990, 464);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 2000, 580);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Mollie", "F", 2010, 674);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1880, 390);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1890, 369);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1900, 410);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1910, 316);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1920, 427);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1930, 362);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1940, 349);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1950, 324);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1960, 359);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1970, 258);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1980, 133);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 1990, 80);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 2000, 95);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Molly", "F", 2010, 87);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1880, 60);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1890, 31);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1900, 19);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1910, 15);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1920, 14);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1930, 12);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1940, 17);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1950, 18);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1960, 18);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1970, 23);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1980, 35);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 1990, 49);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 2000, 100);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Paul", "M", 2010, 177);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1880, 74);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1890, 69);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1900, 84);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1910, 100);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1920, 174);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1930, 214);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1940, 271);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1950, 458);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1960, 832);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1970, 1260);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1980, 656);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 1990, 455);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 2000, 244);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadie", "F", 2010, 118);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Sadye", "F", 1880, 0);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1880, 533);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1890, 436);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1900, 491);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1910, 475);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1920, 847);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1930, 832);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1940, 307);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1950, 241);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1960, 60);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1970, 198);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1980, 672);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 1990, 1278);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 2000, 1382);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Tim", "M", 2010, 2071);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1880, 180);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1890, 221);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1900, 228);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1910, 280);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1920, 363);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1930, 316);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1940, 134);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1950, 32);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1960, 11);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1970, 20);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1980, 20);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 1990, 30);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 2000, 58);
INSERT INTO ranks (name, sex, year, rank) VALUES ("Timothy", "M", 2010, 114);

CREATE TABLE meanings (
  name    varchar(32)  NOT NULL DEFAULT '',
  meaning varchar(512) NOT NULL DEFAULT ''
);
INSERT INTO meanings (name, meaning) VALUES ("Brian", "Irish, English The meaning of this name is not known for certain but it is possibly related to the Old Celtic element bre meaning 'hill', or by extension 'high, noble'.");
INSERT INTO meanings (name, meaning) VALUES ("Dan", "Biblical Means 'he judged' in Hebre; English, Romanian Short form of DANIEL");
INSERT INTO meanings (name, meaning) VALUES ("Daniel", "English, Jewish, French, German, Scandinavian, Polish, Czech, Spanish, Portuguese, Romanian, Biblical From the Hebrew name ????????? (Daniyyel) meaning 'God is my judge'.");
INSERT INTO meanings (name, meaning) VALUES ("Mary", "English, Biblical Usual English form of Maria, which was the Latin form of the New Testament Greek (Mariam) or (Maria) (the spellings are interchangeable), which were from the Hebrew name ??????? (Miryam).");
INSERT INTO meanings (name, meaning) VALUES ("Michael", "English, German, Czech, Biblical From the Hebrew name ???????? (Mika'el) which meant 'who is like God?'.");
INSERT INTO meanings (name, meaning) VALUES ("Mike", "English Short form of MICHAEL");
INSERT INTO meanings (name, meaning) VALUES ("Mollie", "English Pet form of MARY");
INSERT INTO meanings (name, meaning) VALUES ("Molly", "English Pet form of MARY");
INSERT INTO meanings (name, meaning) VALUES ("Paul", "English, French, German, Romanian, Biblical From the Roman family name Paulus, which meant 'small' or 'humble' in Latin.");
INSERT INTO meanings (name, meaning) VALUES ("Sadie", "English Pet form of SARAH");
INSERT INTO meanings (name, meaning) VALUES ("Tim", "English, German Short form of TIMOTHY or TIMON");
INSERT INTO meanings (name, meaning) VALUES ("Timothy", "English, Biblical From the Greek name (Timotheos) meaning 'honouring God', derived from (timao) 'to honour' and (theos) 'god'.");
